#include <keyboard.h>

static const key_t de_keys[] = {
    {0x02, '1', '!'},
    {0x03, '2', '"'},
    {0x04, '3', ' '}, // § (not supported in my current font)
    {0x05, '4', '$'},
    {0x06, '5', '%'},
    {0x07, '6', '&'},
    {0x08, '7', '/'},
    {0x09, '8', '('},
    {0x0A, '9', ')'},
    {0x0B, '0', '='},
    {0x10, 'q', 'Q'},
    {0x11, 'w', 'W'},
    {0x12, 'e', 'E'},
    {0x13, 'r', 'R'},
    {0x14, 't', 'T'},
    {0x15, 'z', 'Z'},
    {0x16, 'u', 'U'},
    {0x17, 'i', 'I'},
    {0x18, 'o', 'O'},
    {0x19, 'p', 'P'},
    {0x1E, 'a', 'A'},
    {0x1F, 's', 'S'},
    {0x20, 'd', 'D'},
    {0x21, 'f', 'F'},
    {0x22, 'g', 'G'},
    {0x23, 'h', 'H'},
    {0x24, 'j', 'J'},
    {0x25, 'k', 'K'},
    {0x26, 'l', 'L'},
    {0x2C, 'y', 'Y'},
    {0x2D, 'x', 'X'},
    {0x2E, 'c', 'C'},
    {0x2F, 'v', 'V'},
    {0x30, 'b', 'B'},
    {0x31, 'n', 'N'},
    {0x32, 'm', 'M'},
    {0x39, ' ', ' '}
};

static const action_key_t de_action_keys[] = {
    {0x01, esc_make, esc_break},
    {0x0C, oem_4_make, oem_4_break},
    {0x0D, oem_6_make, oem_6_break},
    {0x0E, backspace_make, backspace_break},
    {0x0F, tab_make, tab_break},
    {0x1A, oem_1_make, oem_1_break},
    {0x1B, oem_plus_make, oem_plus_break},
    {0x1C, enter_make, enter_break},
    {0x1D, lctrl_make, lctrl_break},
    {0x27, oem_3_make, oem_3_break},
    {0x28, oem_7_make, oem_7_break},
    {0x29, oem_5_make, oem_5_break},
    {0x2A, lshift_make, lshift_break},
    {0x2B, oem_2_make, oem_2_break},
    {0x33, oem_comma_make, oem_comma_break},
    {0x34, oem_period_make, oem_period_break},
    {0x35, oem_minus_make, oem_minus_break},
    {0x36, rshift_make, rshift_break},
    {0x37, multiply_make, multiply_break},
    {0x38, lmenu_make, lmenu_break},
    {0x3A, capslock_make, capslock_break},
    {0x3B, f1_make, f1_break},
    {0x3C, f2_make, f2_break},
    {0x3D, f3_make, f3_break},
    {0x3E, f4_make, f4_break},
    {0x3F, f5_make, f5_break},
    {0x40, f6_make, f6_break},
    {0x41, f7_make, f7_break},
    {0x42, f8_make, f8_break},
    {0x43, f9_make, f9_break},
    {0x44, f10_make, f10_break},
    {0x45, numlock_make, numlock_break},
    {0x46, scrolllock_make, scrolllock_break},
    {0x47, num_home_make, num_home_break},
    {0x48, num_up_make, num_up_break},
    {0x49, num_prior_make, num_prior_break},
    {0x4A, subtract_make, subtract_break},
    {0x4B, num_left_make, num_left_break},
    {0x4C, num_clear_make, num_clear_break},
    {0x4D, num_right_make, num_right_break},
    {0x4E, add_make, add_break},
    {0x4F, num_end_make, num_end_break},
    {0x50, num_down_make, num_down_break},
    {0x51, num_next_make, num_next_break},
    {0x52, num_insert_make, num_insert_break},
    {0x53, num_delete_make, num_delete_break},
    {0x54, snapshot_make, snapshot_break},
    {0x56, oem_102_make, oem_102_break},
    {0x57, f11_make, f11_break},
    {0x58, f12_make, f12_break}
};

static const extended_key_t de_extended_keys[] = {
    {0xE0, 0x1C, num_enter_make, num_enter_break},
    {0xE0, 0x1D, rctrl_make, rctrl_break},
    {0xE0, 0x35, divide_make, divide_break},
    {0xE0, 0x38, rmenu_make, rmenu_break},
    {0xE0, 0x47, home_make, home_break},
    {0xE0, 0x48, up_make, up_break},
    {0xE0, 0x49, prior_make, prior_break},
    {0xE0, 0x4B, left_make, left_break},
    {0xE0, 0x4D, right_make, right_break},
    {0xE0, 0x4F, end_make, end_break},
    {0xE0, 0x50, down_make, down_break},
    {0xE0, 0x51, next_make, next_break},
    {0xE0, 0x52, insert_make, insert_break},
    {0xE0, 0x53, delete_make, delete_break},
    {0xE0, 0x5B, lwin_make, lwin_break},
    {0xE0, 0x5C, rwin_make, rwin_break},
    {0xE0, 0x5D, apps_make, apps_break},
    {0xE1, 0x1D, pause_make, pause_break}
};

const keymap_t keymap_de = {
    .language = "de",
    .keys = de_keys,
    .keys_count = sizeof(de_keys) / sizeof(de_keys[0]),
    .action_keys = de_action_keys,
    .action_keys_count = sizeof(de_action_keys) / sizeof(de_action_keys[0]),
    .extended_keys = de_extended_keys,
    .extended_keys_count = sizeof(de_extended_keys) / sizeof(de_extended_keys[0]),
};
